src/hooks/useHookSetter.tsx

feature: adding useFormSetter Hook

feature: adding useFormSetter Hook

---

package.json
src/app/profile/page.tsx
src/components/landing-page/LadingComponet.tsx
tailwind.config.ts
tsconfig.json

bugfix: some errors have been fixed

bugfix: some errors have been fixed

---

components.json
package.json
src/app/auth/create-profile/page.tsx
src/app/globals.css
src/components/ui/CreateProfileStepper.tsx
src/lib/utils.ts
tailwind.config.ts

feature: adding profile stepper

feature: adding profile stepper

---

src/app/auth/register/page.tsx
src/app/page.tsx
src/components/create-profile/CreateProfileComponent.tsx
src/components/create-profile/RegisterComponent.tsx
src/components/create-profile/stepper/StepOneContent.tsx
src/components/create-profile/stepper/StepThreeContent.tsx
src/components/ui/LoadingSpinner.tsx
src/components/ui/ProfileStepper.tsx
src/components/ui/UploadPhotoProfile.tsx

feature: renaming some files and adding upload photo profile component

feature: renaming some files and adding upload photo profile component

---

README.md

- [] Added tests (if necessary)
- [] Run tests
- [] Run formatting
- [] Commented the code
---
I updated the README.md file to display description about the project.
---
---
---
---

doc: update  README for Project description

---

src/components/register/steps/StepOneContent.tsx

The form was created based on the provided Figma design, ensuring the application of best development practices. **Tailwind CSS** was used for styling, while **Lucide** was utilized for the icons to maintain visual consistency and functionality.
- The form includes fields for **USERNAME**, **EMAIL**, and **LOCATION**, each accompanied by a representative icon.
- Labels for the fields are centered and formatted in bold to clearly indicate the purpose of each input.
- A modern design element was added with bottom borders in `#7649CB` for all input fields.
- The card layout features rounded corners (`rounded-[3rem]`) and a styled border to highlight the form's content.
- Adjustments were made to position the "USERNAME" input closer to the top of the card for improved spacing.
- The structure …

[FE]: Create User Form (Step 1 of the Stepper)

---

__tests__/sample.test.js
babel.config.js
jest.config.js
jest.setup.js
package.json
src/pages/home.jsx

- [ x] Added tests (if necessary)
- [ x] Run tests
- [ x] Evidence attached
---
- [ x] Enhancement (non-breaking change which adds functionality)
---
feat: Add Jest testing configuration and sample test
---
---
---
---

Set Up Jest for Next.js 15 #50

---

package.json
src/app/globals.css
src/app/store/page.tsx
src/components/store/store-profile/StoreAchievements.tsx
src/components/store/store-profile/StoreCategories.tsx
src/components/store/store-profile/StoreHeader.tsx
src/components/store/store-profile/StoreStats.tsx
src/components/ui/button.tsx

---
---
The original monolithic store profile page has been broken down into smaller, reusable components following React best practices and the single responsibility principle.
```
components/store/
├── StoreHeader.tsx
├── StoreStats.tsx
├── StoreCategories.tsx
└── StoreAchievements.tsx
app/
└── store/
└── page.tsx
```
**Purpose**: Displays store profile information
**Key Features**:
- Store logo with Image component
- Store name and description
- Contact information (location, website, email)
- Edit store button
- Responsive layout (mobile-first approach)
**Purpose**: Shows key store metrics
**Key Features**:
- TypeScript interface for stat items
- Grid layout for statistics
- Responsive design (1 column on mobile, 3 columns on …

Feat: create profile screen

---

src/app/globals.css
src/components/billing/current-plan.tsx

- [ x] Closes #65 
---
---
I created a responsive component for the current plan section of the project, following the figma design.
Note: In the demo I placed the component in any area of the project just to show that the interface complies with the request.
---
[Demo](https://youtu.be/-b71JHJ7AbQ)
---
2 hours
---
---

feat: creact current plan section

---

src/components/billing/manual-payment.tsx

---
---
This PR introduces the ManualPayment component, which provides a form for making manual XLM payments. 
Key features:
- Two input fields (XLM Amount and Memo) aligned side-by-side on larger screens.
- A submit button that triggers placeholder logic until backend integration is ready.
- Responsive layout and styling consistent with the ConnectedWallet component.
- Uses Tailwind CSS and React hooks for state management.
---
https://www.loom.com/share/dcd4fafd9f884a0f8c45e5675a7623c1?sid=0f67ffba-afc9-494e-931b-2146fee950ef
---
1 day
---
Thanks for the opportunity
---

feat: Implement Manual Payment Component with Form Submission and Placeholder Logic

---

src/app/faq/page.tsx
src/components/features/faq/FAQSupportSection.tsx

- Added FAQSupportSection component with "Still Have Questions?" section on faq page.
---
---
- Added FAQSupportSection component with "Still Have Questions?" section.
- Included Contact Support and Visit Community Forum buttons.
---
---
3 hours
---
---

Feat: implement Still Have Questions section.

---

package.json
src/components/features/user/nfts/components/NFTCollectionOverview.tsx
src/components/features/user/nfts/components/StatsCard .tsx
src/components/features/user/profile/UserProfile.tsx

This PR implements the NFT Collection Overview Section at the top of the page, providing users with a summary of their NFTs. The section includes key statistics and a search bar for filtering NFTs.
- [x ] Run tests
- [ x] Evidence attached
- [ x] Commented the code
---
- [ x] Enhancement (non-breaking change which adds functionality)
- [x ] Breaking change (fix or feature that would cause existing functionality to change)
---
- **New Components:**
- `NFTCollectionOverview.tsx`: Main component for the NFT Collection Overview Section.
- `NFTSearchBar.tsx`: Search bar component for filtering NFTs by name, ID, or store.
- **Features:**
- Display of total NFTs owned.
- Display of clothing rewards earned.
- Display of redeemable …

Feat:Implement NFT Collection Overview Section

---

package.json
src/app/globals.css
src/app/user/invoices/page.tsx
src/features/user/invoices/components/RecentInvoicesTable.tsx
tailwind.config.ts

Mark with an `x` all the checkboxes that apply (like `[x]`)  
---
---
- Displayed invoice details, including:  
- **Product Name (Invoice Name)**  
- **Invoice ID**  
- **Store Name**  
- **Invoice Date**  
- **Total Amount (XLM)**  
- **Status (Paid, Pending, Overdue)**  
- Added **"View"** and **"Download"** buttons as actions for each invoice  
- Implemented a **"Load More Invoices"** button for fetching additional invoices  
- Styled using **Tailwind CSS** with proper **typography, spacing, and colors**  
- Ensured **consistent design** by aligning with Figma specifications  
- **Fixed hover effects**, borders, and button styling to match design requirements  
- Made **fully responsive** for mobile, tablet, and desktop views  
---
---
Thank you for contributing to StarShop, we are …

Impl: Recent Invoices Table

---

README.md

docs: fixed link readme

---

src/app/example/page.tsx
src/components/features/user/support/components/TicketDetails.tsx

`[x]` Closes #113 
`[x]` Added tests (if necessary)
`[x]` Run tests
`[x]` Run formatting
`[x]` Evidence attached
`[x]` Commented the code
---
- Documentation (updates to README, docs, or comments)
- Bug fix (non-breaking change which fixes an issue)
- Enhancement (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)
---
Enhanced the EmptyTicketState component with the following visual improvements:
- Added a subtle border with reduced opacity to match the design
- Implemented a semi-transparent white background (20% opacity) for depth
- Created a subtle star/dot pattern in the background for visual interest
- Improved component structure with proper …

feat: tickets details and creation panel

---

src/app/user/analytics/page.tsx
src/components/features/user/analytics/AnalyticsCard.tsx
src/components/features/user/analytics/AnalyticsHeader.tsx
src/components/features/user/analytics/AnalyticsSummary.tsx
src/components/features/user/analytics/GlowCard.tsx

---
---
Added a new Analytics Dashboard feature with the following components:
1. Created new Analytics page with responsive layout
2. Implemented Analytics components:
- AnalyticsHeader: Features period selection, custom date range, export, and refresh functionality
- AnalyticsSummary: Displays key metrics in a grid layout
- AnalyticsCard: Reusable component for displaying metric cards with progress bars
- GlowCard: Visual component for enhanced UI
Key metrics included:
- Total Revenue
- Total Orders
- Conversion Rate
- Total Visitors
Features:
- Period comparison toggle
- Custom date range selection
- Data export functionality
- Real-time refresh option
- Progress tracking against targets
- Period-over-period change indicators …

Feat: Implement Analytics Summary Section

---

src/components/features/user/analytics/DeviceProductsActivity.tsx

---
---
This PR implements the Device Breakdown, Top Products & Recent Activity section to provide insights into visitor behavior and store performance.
- Add device breakdown chart showing visitor distribution by device type (Mobile, Desktop, Tablet)
- Implement top products section with sales data and XLM values
- Create recent activity section with orders, reviews, and product views
- Ensure responsive design across all device sizes
- Add view all buttons for products and activity sections
- Verified responsive behavior on mobile, tablet, and desktop views
- Confirmed correct rendering of all data points and charts
- Tested view all buttons functionality
---
---
4 hours
---
-
---
Thank you for contributing to StarShop, we are …

feat: implement device breakdown, top products & recent activity

---

src/app/user/nft-collection/page.tsx
src/components/features/user/nfts/components/ExclusiveNFTRewards.tsx
src/components/features/user/nfts/components/NFTRewardCard.tsx
src/components/ui/badge.tsx

---
---
- Implemented the `ExclusiveNFTRewards` component according to the Figma design.
- Built two main sections: `Purchase Rewards` and `NFT Coupons & Vouchers`.
- Added card visuals, spacing, and iconography with responsive support.
- Enhanced layout for mobile and desktop.
- Customized style and height for NFT cards and content alignment.
- Used Tailwind utility classes for consistency and maintainability.
- Final UI matches design closely and behaves well across screen sizes.
---
---
**Total**: ~7 hours
---
This feature improves user engagement by visually showcasing NFT-based incentives in a clean, structured and fully responsive layout.  
All styles align with the current design system.  
Feedback is welcomed!
---
Thank …

feat: implement Exclusive NFT Rewards section

---

package.json
src/app/user/analytics/page.tsx
src/components/features/analytics/components/RevenueOverview.tsx
src/components/features/analytics/components/RevenueTrafficOverview.tsx
src/components/features/analytics/components/Tabs.tsx
src/components/features/analytics/components/TrafficSources.tsx

---
---
Created a new component `RevenueTrafficOverview` with the following sub-component with features:
- `Tabs.tsx`: Navigation tabs (Overview, Sales, Traffic, Products, Customers)
- `RevenueOverview.tsx`: Revenue Overview chart showing monthly revenue trends
- `TrafficSources.tsx`: Traffic Sources visualization with pie chart and progress bars
- Responsive design that works on all screen sizes
---
---
- Used Recharts for data visualization
- Implemented custom canvas for the space-themed background effect
- Used CSS for glowing borders and semi-transparent elements
- Split the component into smaller, reusable parts for better maintainability
- Added responsive design with Tailwind CSS grid system
---
---
Thank you for …

feat: Implement Revenue & Traffic Overview Section

---

src/app/page.tsx
src/components/features/user/support/components/TicketOverview.tsx
src/components/features/user/support/components/mock/data-ticket-overview.ts
src/components/features/user/support/components/types/ticket.ts
src/components/ui/StarShopCard.tsx

---
---
- Implemented the support tickets overview section at the top of the page.
- Displayed ticket statistics: total tickets, open tickets (highlighting urgent ones), in-progress tickets (with average resolution time), and resolved tickets (count for the last 7 days).
- Added response time bar showing average response time and SLA (target response time).
- Ensured the section is fully responsive with proper typography, spacing, and colors.
---
- The section is now fully integrated and responsive.
- Further testing required for specific mobile screen sizes.

Support tickets overview

---

src/app/products/page.tsx
src/components/features/store/create-store-form.tsx
src/components/features/store/dashboard/components/RecentOrder.tsx
src/components/features/store/dashboard/components/SalesGoalCard.tsx
src/components/features/store/dashboard/messages/MessagesWindow.tsx
src/components/features/store/product/InventoryStatus.tsx
src/components/features/store/product/ProductPerformance.tsx
src/components/features/store/product/QuickActions.tsx
src/components/features/store/transactions/Transaction.tsx
src/components/features/user/invoices/components/RecentInvoicesTable.tsx
src/components/invoices/InvoiceList.tsx

feat: Implement Product Dashboard UI with responsiveness

---

src/app/auth/login/page.tsx
src/app/dashboard/page.tsx
src/app/layout.tsx
src/components/auth/NavigationGuard.tsx
src/components/auth/UserMenu.tsx
src/context/AuthProvider.tsx
src/hooks/useAuth.ts
src/types/user.types.ts
src/utils/encryptJWT.ts

---
---
This pull request introduces a new authentication system and role-based access control for the `StarShop` application. It includes the implementation of login functionality, user session management, and protected routes, along with updates to the dashboard and layout to integrate these features.
* Added an `AuthProvider` context to manage user sessions, including login, logout, and role updates. It persists user data in `localStorage` for session continuity. (`src/context/AuthProvider.tsx`, [src/context/AuthProvider.tsxR1-R85](diffhunk://#diff-7d6b42ef87e20642f33cfed5353d6db82a1cbc4449d51c5ac371170fb735bc34R1-R85))
* Created a `useAuth` hook to provide easy access to authentication methods and user state throughout the …

feat: implement authentication context and user session management

---

src/utils/formatCurrency.ts

---
---
Added a fuction which accept the currency, amount and locale to format each currency to the user local currency.
---
---
I spent just 45 min in getting the logics to format the code
---
---

formatCurrency-function created

---

src/app/page.tsx
src/hooks/useWebSocket.ts

---
---
Added a reusable React hook useWebSocket that handles WebSocket connections with proper lifecycle management. This hook simplifies WebSocket integration in React components by providing:
Automatic connection establishment and cleanup
Real-time message handling via the lastMessage state
Connection state tracking through readyState
Simplified message sending with the send function
Complete unmount cleanup to prevent memory leaks
The hook follows a clean, standardized API pattern: useWebSocket(url): { send, lastMessage, readyState } making it easy to integrate across different components that require WebSocket functionality.
---
---
2 hours
---
Here is an example of how to use the `useWebSocketHook` i created in this PR …

feat: add WebSocket hook and update landing page component structure

---

.gitignore
src/hooks/useDebounce.ts

---
---
Added a reusable `useDebounce` hook to delay value updates based on idle time.
---
---
- 15 minutes planning and understanding requirements
- 35 minutes coding
- 5 minutes testing
- 5 minutes writing the PR
---
First contribution! Really excited to work on this project 🎉. Looking forward to contributing more
---

Use debounce issue

---

src/lib/types/user.ts
src/store/useSessionStore.ts

Implement user session management with Zustand store
---
---
Introduce a Zustand store for managing user sessions, including login, logout, and user role management. This implementation supports persistence in localStorage.
---
---
---
---

feat: add user session management with Zustand store

---

package.json
src/hooks/useOptimizedProductPrefetch.ts
src/lib/api/products.ts
src/types/product.ts

---
---
This PR introduces the `useOptimizedProductPrefetch` hook to enable intelligent acceleration of the product page experience in the StarShop frontend.
The hook:
- Prefetches product detail data via React Query
- Preloads associated image assets based on product ID
- Triggers prefetching on hover (onMouseEnter) and mobile touch (onTouchStart)
- Uses React 18’s `startTransition` to avoid blocking UI rendering
- Calls `router.prefetch` in App Router to prefetch the product route
This functionality is isolated and ready to be used on any product card component.
---
- Hook creation and logic: 30 mins
- Environment and structure setup: 15 mins
- Manual testing and network validation: 15 mins
- Writing documentation and PR: 10 …

feat:useOptimizedProductPrefetch

---

bun.lock
src/app/page.tsx
src/components/features/user/faq/FAQCategories.tsx
src/hooks/useIsFirstRender.ts

---
---
`useIsFirstRender` hook
-  Returns `true` only on the component’s first render.
-  Returns `false` on all subsequent renders.
```typescript
import React, { useEffect } from 'react';
import { useIsFirstRender } from './useIsFirstRender';
function MyComponent() {
const isFirstRender = useIsFirstRender();
useEffect(() => {
if (isFirstRender) {
console.log('Only runs on first render');
// Run your one-time mount logic here
}
}, [isFirstRender]);
return (
<div>
<h1>Hello World</h1>
{isFirstRender && <p>This message is only shown on the first render.</p>}
</div>
);
}
``` 
---
20 minutes
Thank you for contributing to StarShop, we are glad that you have chosen us as your project of choice and we hope that you continue to …

feat: build useIsFirstRender hook

---

src/components/ui/Input.tsx
src/features/store/invoices/components/invoice-details.tsx
src/lib/utils.ts

fix: some erros were fixed

---

src/features/common/landing/content/network-performance/NetworkPerformance.tsx
src/features/common/landing/content/network-performance/components/LiveStatusIndicator.tsx
src/features/common/landing/content/network-performance/components/NetworkMetrics.tsx
src/features/common/landing/content/network-performance/constants/network-performance.ts

feat: Implement network-performance component

---

src/app/page.tsx
src/features/common/landing/components/trusted-by/index.ts
src/features/common/landing/components/trusted-by/trusted-by.tsx

Added a new TrustedBy component to the landing page, featuring brand chips and a clean, modern design.
Closes #245 
- Created responsive TrustedBy component with brand chips
- Added gradient background with subtle pattern overlay
- Implemented responsive design for all screen sizes
- Integrated with the main landing page layout

feat: add TrustedBy component to landing page

---

src/shared/services/crowdfunding_collective/README.md
src/shared/services/crowdfunding_collective/constants/crowdfunding.constants.ts
src/shared/services/crowdfunding_collective/crowdfunding.service.ts
src/shared/services/crowdfunding_collective/index.ts
src/shared/services/crowdfunding_collective/types/crowdfunding.types.ts
src/shared/services/crowdfunding_collective/types/events.types.ts
src/shared/services/crowdfunding_collective/utils/crowdfunding.utils.ts

feat: Implement binding crowdfunding contract
